=== garretthunter/eqdkp-setprogress/xml/wow_sets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="categoryType">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element name="class" type="classType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="classType">
		<xs:sequence>
			<xs:element ref="class_name"/>
			<xs:element name="set" type="setType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="class_name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Druid"/>
				<xs:enumeration value="Hunter"/>
				<xs:enumeration value="Mage"/>
				<xs:enumeration value="Paladin"/>
				<xs:enumeration value="Priest"/>
				<xs:enumeration value="Rogue"/>
				<xs:enumeration value="Shaman"/>
				<xs:enumeration value="Warlock"/>
				<xs:enumeration value="Warrior"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:complexType name="pieceType">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="requirement" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="requirement" type="xs:string"/>
	<xs:complexType name="setType">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element name="piece" type="pieceType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="wow_sets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="category" type="categoryType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== garretthunter/eqdkp-setprogress/xml/setprogress.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by LoganFive (LoganFive) -->
<wow_sets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\WebDesign\SleeplessKnights\rap\plugins\setprogress\xml\wow_sets.xsd">
	<category>
		<name>Tier 1</name>
		<class>
			<class_name>Druid</class_name>
			<set>
				<name>Cenarian Raiment</name>
				<piece>
					<name>Cenarion Belt</name>
				</piece>
				<piece>
					<name>Cenarion Boots</name>
				</piece>
				<piece>
					<name>Cenarion Bracers</name>
				</piece>
				<piece>
					<name>Cenarion Gloves</name>
				</piece>
				<piece>
					<name>Cenarion Helm</name>
				</piece>
				<piece>
					<name>Cenarion Leggings</name>
				</piece>
				<piece>
					<name>Cenarion Spaulders</name>
				</piece>
				<piece>
					<name>Cenarion Vestments</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Hunter</class_name>
			<set>
				<name>Giantstalker Armor</name>
				<piece>
					<name>Giantstalker's Belt</name>
				</piece>
				<piece>
					<name>Giantstalker's Boots</name>
				</piece>
				<piece>
					<name>Giantstalker's Bracers</name>
				</piece>
				<piece>
					<name>Giantstalker's Gloves</name>
				</piece>
				<piece>
					<name>Giantstalker's Helmet</name>
				</piece>
				<piece>
					<name>Giantstalker's Leggings</name>
				</piece>
				<piece>
					<name>Giantstalker's Epaulets</name>
				</piece>
				<piece>
					<name>Giantstalker's Breastplate</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Mage</class_name>
			<set>
				<name>Arcanist Regalia</name>
				<piece>
					<name>Arcanist Belt</name>
				</piece>
				<piece>
					<name>Arcanist Boots</name>
				</piece>
				<piece>
					<name>Arcanist Bindings</name>
				</piece>
				<piece>
					<name>Arcanist Gloves</name>
				</piece>
				<piece>
					<name>Arcanist Crown</name>
				</piece>
				<piece>
					<name>Arcanist Leggings</name>
				</piece>
				<piece>
					<name>Arcanist Mantle</name>
				</piece>
				<piece>
					<name>Arcanist Robes</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Paladin</class_name>
			<set>
				<name>Lawbringer Armor</name>
				<piece>
					<name>Lawbringer Belt</name>
				</piece>
				<piece>
					<name>Lawbringer Boots</name>
				</piece>
				<piece>
					<name>Lawbringer Bracers</name>
				</piece>
				<piece>
					<name>Lawbringer Gauntlets</name>
				</piece>
				<piece>
					<name>Lawbringer Helm</name>
				</piece>
				<piece>
					<name>Lawbringer Legplates</name>
				</piece>
				<piece>
					<name>Lawbringer Spaulders</name>
				</piece>
				<piece>
					<name>Lawbringer Chestguard</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Priest</class_name>
			<set>
				<name>Vestments of Prophecy</name>
				<piece>
					<name>Girdle of Prophecy</name>
				</piece>
				<piece>
					<name>Boots of Prophecy</name>
				</piece>
				<piece>
					<name>Vambraces of Prophecy</name>
				</piece>
				<piece>
					<name>Gloves of Prophecy</name>
				</piece>
				<piece>
					<name>Circlet of Prophecy</name>
				</piece>
				<piece>
					<name>Pants of Prophecy</name>
				</piece>
				<piece>
					<name>Mantle of Prophecy</name>
				</piece>
				<piece>
					<name>Robes of Prophecy</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Rogue</class_name>
			<set>
				<name>Nightslayer Armor</name>
				<piece>
					<name>Nightslayer Belt</name>
				</piece>
				<piece>
					<name>Nightslayer Boots</name>
				</piece>
				<piece>
					<name>Nightslayer Bracelets</name>
				</piece>
				<piece>
					<name>Nightslayer Gloves</name>
				</piece>
				<piece>
					<name>Nightslayer Cover</name>
				</piece>
				<piece>
					<name>Nightslayer Pants</name>
				</piece>
				<piece>
					<name>Nightslayer Shoulder Pads</name>
				</piece>
				<piece>
					<name>Nightslayer Chestpiece</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Shaman</class_name>
			<set>
				<name>The Earthfury</name>
				<piece>
					<name>Earthfury Belt</name>
				</piece>
				<piece>
					<name>Earthfury Boots</name>
				</piece>
				<piece>
					<name>Earthfury Bracers</name>
				</piece>
				<piece>
					<name>Earthfury Gauntlets</name>
				</piece>
				<piece>
					<name>Earthfury Helmet</name>
				</piece>
				<piece>
					<name>Earthfury Legguards</name>
				</piece>
				<piece>
					<name>Earthfury Epaulets</name>
				</piece>
				<piece>
					<name>Earthfury Vestments</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Warlock</class_name>
			<set>
				<name>Felheart Raiment</name>
				<piece>
					<name>Felheart Belt</name>
				</piece>
				<piece>
					<name>Felheart Slippers</name>
				</piece>
				<piece>
					<name>Felheart Bracers</name>
				</piece>
				<piece>
					<name>Felheart Gloves</name>
				</piece>
				<piece>
					<name>Felheart Horns</name>
				</piece>
				<piece>
					<name>Felheart Pants</name>
				</piece>
				<piece>
					<name>Felheart Shoulder Pads</name>
				</piece>
				<piece>
					<name>Felheart Robes</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Warrior</class_name>
			<set>
				<name>Battlegear of Might</name>
				<piece>
					<name>Belt of Might</name>
				</piece>
				<piece>
					<name>Sabatons of Might</name>
				</piece>
				<piece>
					<name>Bracers of Might</name>
				</piece>
				<piece>
					<name>Gauntlets of Might</name>
				</piece>
				<piece>
					<name>Helm of Might</name>
				</piece>
				<piece>
					<name>Legplates of Might</name>
				</piece>
				<piece>
					<name>Pauldrons of Might</name>
				</piece>
				<piece>
					<name>Breastplate of Might</name>
				</piece>
			</set>
		</class>
	</category>
	<category>
		<name>Tier 2</name>
		<class>
			<class_name>Druid</class_name>
			<set>
				<name>Stormrage Raiment</name>
				<piece>
					<name>Stormrage Belt</name>
				</piece>
				<piece>
					<name>Stormrage Boots</name>
				</piece>
				<piece>
					<name>Stormrage Bracers</name>
				</piece>
				<piece>
					<name>Stormrage Handguards</name>
				</piece>
				<piece>
					<name>Stormrage Cover</name>
				</piece>
				<piece>
					<name>Stormrage Legguards</name>
				</piece>
				<piece>
					<name>Stormrage Pauldrons</name>
				</piece>
				<piece>
					<name>Stormrage Chestguard</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Hunter</class_name>
			<set>
				<name>Dragonstalker Armor</name>
				<piece>
					<name>Dragonstalker's Belt</name>
				</piece>
				<piece>
					<name>Dragonstalker's Greaves</name>
				</piece>
				<piece>
					<name>Dragonstalker's Bracers</name>
				</piece>
				<piece>
					<name>Dragonstalker's Gauntlets</name>
				</piece>
				<piece>
					<name>Dragonstalker's Helm</name>
				</piece>
				<piece>
					<name>Dragonstalker's Legguards</name>
				</piece>
				<piece>
					<name>Dragonstalker's Spaulders</name>
				</piece>
				<piece>
					<name>Dragonstalker's Breastplate</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Mage</class_name>
			<set>
				<name>Netherwind Regalia</name>
				<piece>
					<name>Netherwind Belt</name>
				</piece>
				<piece>
					<name>Netherwind Boots</name>
				</piece>
				<piece>
					<name>Netherwind Bindings</name>
				</piece>
				<piece>
					<name>Netherwind Gloves</name>
				</piece>
				<piece>
					<name>Netherwind Crown</name>
				</piece>
				<piece>
					<name>Netherwind Pants</name>
				</piece>
				<piece>
					<name>Netherwind Mantle</name>
				</piece>
				<piece>
					<name>Netherwind Robes</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Paladin</class_name>
			<set>
				<name>Judgement Armor</name>
				<piece>
					<name>Judgement Belt</name>
				</piece>
				<piece>
					<name>Judgement Sabatons</name>
				</piece>
				<piece>
					<name>Judgement Bindings</name>
				</piece>
				<piece>
					<name>Judgement Gauntlets</name>
				</piece>
				<piece>
					<name>Judgement Crown</name>
				</piece>
				<piece>
					<name>Judgement Legplates</name>
				</piece>
				<piece>
					<name>Judgement Spaulders</name>
				</piece>
				<piece>
					<name>Judgement Breastplate</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Priest</class_name>
			<set>
				<name>Vestments of Transcendence</name>
				<piece>
					<name>Girdle of Prophecy</name>
				</piece>
				<piece>
					<name>Boots of Prophecy</name>
				</piece>
				<piece>
					<name>Vambraces of Prophecy</name>
				</piece>
				<piece>
					<name>Gloves of Prophecy</name>
				</piece>
				<piece>
					<name>Circlet of Prophecy</name>
				</piece>
				<piece>
					<name>Pants of Prophecy</name>
				</piece>
				<piece>
					<name>Mantle of Prophecy</name>
				</piece>
				<piece>
					<name>Robes of Prophecy</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Rogue</class_name>
			<set>
				<name>Bloodfang Armor</name>
				<piece>
					<name>Bloodfang Belt</name>
				</piece>
				<piece>
					<name>Bloodfang Boots</name>
				</piece>
				<piece>
					<name>Bloodfang Bracers</name>
				</piece>
				<piece>
					<name>Bloodfang Gloves</name>
				</piece>
				<piece>
					<name>Bloodfang Hood</name>
				</piece>
				<piece>
					<name>Bloodfang Pants</name>
				</piece>
				<piece>
					<name>Bloodfang Spaulders</name>
				</piece>
				<piece>
					<name>Bloodfang Chestpiece</name>
				</piece>
			</set>
		</class>
		<class>
			<class_name>Shaman</class_name>
			<set>
				<name>The Ten Storms</name>
				<piece>
